### ISSUE TITLE
Trying to build on nvidia

### ISSUE THREAD

**Issue by griz1112** [OpenSolo/sololink#1]
The version of gstreamer this code wants is no longer supplied with ubuntu especially on the nvidia which has its own enhanced version of gstreamer1.0 instead of 0.1.0. 1.0 has been the standard version since 2012 so I don't expect this build to go smoothly without a lot of work on the video section on up to date versions of linux.

**Comment by davidbuzz** [comment]
The build uses vagrant, so all compilation occurs inside a standard ubuntu 12 Vzm

**Comment by davidbuzz** [comment]
... see solo-builder repo for the vagrant/ubuntu build environment.  It builds fine that way.
