### ISSUE TITLE
Let's make it universal rc/telemetry/video transmission system

### ISSUE THREAD

**Issue by bazyl78** [OpenSolo/sololink#3]
I have a crazy idea that it would be nice to make another branch of opensolo to create something like ligtbridge / Cuav Hacklink

Hardware: only solo link board and controller link board (no buttons, lcd screen, etc.)
- ppm input pin (RC control) on controller board
- wifi hotspot on controller board (to connect to Tower / QGroundcontrol for video and telemetry)
- telemetry input on solo link board
- video input on solo link board (hdmi)

Software:
- simple video downlink, telemetry and rc passthrough + failsafe
- removed other scripts / programs (smart shots, display control, buttons control, etc.)

It should work like CUAV Hacklink (https://www.banggood.com/en/CUAV-HACK-LINK-2_4G-UAV-Digital-Link-System-HDMI-PPM-Mavlink-Data-Transmission-For-PIXHACK-PIXHAWK-p-1130256.html):
- you connect controller link to GCS via WIFI (QGroundcontrol / Tower)
- rc ppm/sbus signal is transmitted to drone over WIFI from external transmitter connected to controller board
- video can be watched i GCS in widget window (solo video stream or custom UDP)

I would love to do it myself but current software has so many components and pins on controller link board are not documented :-(. Plus I'm not a very good programmer.

**Comment by FLYBYME** [comment]
The Cuav Hacklink uses the same source code as sololink.

**Comment by samiahmari** [comment]
PPM feature is really essential for DIY people. There is not much of rc control channels on solo controller makes it impossible  to use it for DIY project. 
CUAV Hacklink supports ppm and their software and hardware is open :
https://github.com/cuav

**Comment by FLYBYME** [comment]
From what I understand we only have 2 gpio pin 19 and 21 that are used for switching usb devices. Other then that I dont know what could be use to output the ppm signal.

**Comment by samiahmari** [comment]
@FLYBYME  Is it possible to configure current dsm pin for cppm or usb select gpio? The idea is to have sololink as generic data and video link for any kind of transmitter with cppm like Taranis and any kind of Pixhawk based FC with any kind of firmware (rover,vtol, plane ....). In these cases those USB pins will not being used at all.  Right now I am doing the same but I am stock with Solo transmitter with potentially just 8 channels over DSM.

**Comment by FLYBYME** [comment]
DSM goes over serial and I dont think you can manipulate the tx or rx pins in the way you need to for ppm.

**Comment by bazyl78** [comment]
Then at least sbus could be posible :)

**Comment by davidbuzz** [comment]
issues list is for issues/bugs, not feature requests.  If someone plans to actually implement anything discussed here, fabulous, and please raise a PR for it, we'd love to see .

**Comment by FLYBYME** [comment]
Where should we me making feature requests?
