### ISSUE TITLE
Current development fork

### ISSUE THREAD

**Issue by FLYBYME** [OpenSolo/sololink#4]
Current development is taking place in Pedals2Paddles [fork](https://github.com/Pedals2Paddles/sololink) until he feels comfortable to take it our of beta. I thought I would let all who are wondering where the release candidate are coming from.

**Comment by davidbuzz** [comment]
rc work has been merged to master, this issue is no longer accurate

**Comment by FLYBYME** [comment]
Again it has changed..
https://github.com/Pedals2Paddles/OpenSolo
